### ISSUE TITLE
Provide readymade containers

### ISSUE THREAD

**Issue by usego** [lstrojny/prometheus-weathermen#51]
Please add Dockerfile so it's easier to try this exporter by anyone unfamiliar with Rust

**Comment by lstrojny** [comment]
Are you looking for a development environment Dockerfile or an environment to run the exporter?

**Comment by usego** [comment]
> Are you looking for a development environment Dockerfile or an environment to run the exporter?

Env to run with docker could be nice to have for quick testing and hopefully further usage at prod :)

**Comment by lstrojny** [comment]
Got it. Let me check out how other exporters provide readymade containers

**Comment by lstrojny** [comment]
For now you can pick a minimal container, e.g. alpine and copy the pre-built binary + config into it (for Linux pick the static ones)
